#Exercise 1.A NumPy: Manipulating Arrays

In [1]:
import numpy as np

##Looping Through Arrays

In [2]:
arrA = np.array([[11, 12, 13], [14, 15, 16]])

print(arrA)

[[11 12 13]
 [14 15 16]]


In [3]:
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [4]:
for x in arrA:
    for y in x:
        print(y * 2)

22
24
26
28
30
32


The first loop goes through each row in the array, so it multiplies each row by 2 and prints the rows.

The second loop goes inside each row and prints each individual number multiplied by 2.

In [5]:
for x in arrA:
    for y in x:
        loop_result = x * 2
        print(loop_result)

# This result is different because even though y loops through each number,
# the code is multiplying x by 2, not y.
# Since x is the whole row, it prints the doubled row multiple times.

[22 24 26]
[22 24 26]
[22 24 26]
[28 30 32]
[28 30 32]
[28 30 32]


##Joining and Stacking Arrays

In [6]:
joined_array_1 = np.concatenate((arrA, arrA), axis=0)

print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [7]:
joined_array_2 = np.concatenate((arrA, arrA), axis=1)

print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [8]:
stacked_array_1 = np.stack((joined_array_1, joined_array_1))

print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [9]:
stacked_array_2 = np.stack((joined_array_1, joined_array_2))

print(stacked_array_2)

# Error explanation:
# This gives an error because joined_array_1 and joined_array_2 have different shapes.
# NumPy cannot stack arrays unless they have the same shape.

ValueError: all input arrays must have the same shape

In [10]:
another_joined_array = np.concatenate((joined_array_1, arrA))

print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [11]:
another_2 = np.concatenate((joined_array_1, arrA), axis=1)

print(another_2)

# Error explanation:
# This gives an error because the arrays do not have the same number of rows.
# joined_array_1 has 4 rows, but arrA has 2 rows.

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

In [14]:
h_stack = np.hstack((arrA, arrA))
# hstack stacks arrays horizontally, side by side.

v_stack = np.vstack((arrA, arrA))
# vstack stacks arrays vertically, one on top of the other.

d_stack = np.dstack((arrA, arrA))
# dstack stacks arrays depth-wise, creating a new third dimension.

print(h_stack)
print(v_stack)
print(d_stack)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]
[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]
[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


##Splitting Arrays

In [13]:
splitsky = np.array_split(joined_array_1, 2)

print(splitsky)

# This creates 2 arrays.
# Each array is 2-dimensional.

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [15]:
spliterino = np.array_split(joined_array_1, 3)

print(spliterino)

# This creates 3 arrays.
# Each array is 2-dimensional, but they are not all the same size.

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


##Searching and Replacing Array Values

In [16]:
result_1 = np.where(arrA % 2 == 0, arrA, "odd")

print(result_1)

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


##Sorting and Filtering Arrays

In [17]:
arrB = np.array([[7, 6], [13, 5], [7, 3]])

arrB_sorted = np.sort(arrB)

print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [18]:
print(arrB)

z = arrB < 7

arrC = arrB[z]

print(arrC)

[[ 7  6]
 [13  5]
 [ 7  3]]
[6 5 3]


In [19]:
print(arrB)

y = arrB >= 7

arrD = arrB[y]

print(arrD)

[[ 7  6]
 [13  5]
 [ 7  3]]
[ 7 13  7]
